title: Osmania University Materials
description: Free resources, notes, and materials for OU students
theme: minima
baseurl: "" # Keep blank for GitHub Pages
url: "https://your-username.github.io/osmania-materials"
